name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare
      run: make prepare

    - name: Run tests
      run: make test

    - name: Build
      run: make build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: target/release/rtpl
        retention-days: 15
        overwrite: true
          
